<a href="https://colab.research.google.com/github/Priyanshi-Data-Art/Numpy/blob/main/Numpy_Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np
a1=np.random.randint(1,100,(3,3))
print(f"Original array :\n {a1}\n and Interchange array :\n {a1.T}\n")

Original array :
 [[22 17 51]
 [99  7 80]
 [44 36 27]]
 and Interchange array :
 [[22 99 44]
 [17  7 36]
 [51 80 27]]



Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array


In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(f"dimensional of an array : {a.ndim}\n")
print(f"Reshaping it to 2*5 :\n {a.reshape((2,5))}")
print(f"Reshaping it to 5*2 :\n {a.reshape((5,2))}")

[ 1  2  3  4  5  6  7  8  9 10]
dimensional of an array : 1

Reshaping it to 2*5 :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reshaping it to 5*2 :
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [3]:
a=np.random.rand(4,4)
print(a)
array=np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(f"\nArray :-\n{array}")

[[0.51781387 0.96407781 0.11050452 0.29999339]
 [0.93770108 0.64796625 0.9183457  0.65672786]
 [0.91194615 0.90194645 0.30758374 0.59415766]
 [0.50057986 0.73150294 0.20564363 0.06451579]]

Array :-
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.51781387 0.96407781 0.11050452 0.29999339 0.        ]
 [0.         0.93770108 0.64796625 0.9183457  0.65672786 0.        ]
 [0.         0.91194615 0.90194645 0.30758374 0.59415766 0.        ]
 [0.         0.50057986 0.73150294 0.20564363 0.06451579 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
ar1=np.arange(10,61,5)
ar1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [5]:
str_array=np.array(['python', 'numpy', 'pandas'])
uppercase=np.char.upper(str_array)
lowercase=np.char.lower(str_array)
title_case=np.char.title(str_array)

print(f"Uppercase:={uppercase} \nLowercase:={lowercase} \nTitle case:= {title_case}")

Uppercase:=['PYTHON' 'NUMPY' 'PANDAS'] 
Lowercase:=['python' 'numpy' 'pandas'] 
Title case:= ['Python' 'Numpy' 'Pandas']


Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [6]:
import numpy as np
ch=np.array(['this', 'is', 'the', 'pen'])
np.char.join(' ',ch)

array(['t h i s', 'i s', 't h e', 'p e n'], dtype='<U7')

Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [7]:
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,5,(3,3))
print(f"array1=\n{arr1}\n array2=\n{arr2}")
print(f"dimension of an array : {arr1.ndim}")
# Element wise addition
print(f"Addition of two array :\n {arr1+arr2}")

# Element wise Subtraction
print(f"Subtration of two array :\n {arr1-arr2}")

# Element wise multiplication
print(f"Multiplication of two array :\n {arr1*arr2}")

# Element wise Division
print(f"Division of two array :\n {arr1/arr2}")

array1=
[[4 3 4]
 [4 4 1]
 [1 1 2]]
 array2=
[[4 1 3]
 [4 3 3]
 [4 2 4]]
dimension of an array : 2
Addition of two array :
 [[8 4 7]
 [8 7 4]
 [5 3 6]]
Subtration of two array :
 [[ 0  2  1]
 [ 0  1 -2]
 [-3 -1 -2]]
Multiplication of two array :
 [[16  3 12]
 [16 12  3]
 [ 4  2  8]]
Division of two array :
 [[1.         3.         1.33333333]
 [1.         1.33333333 0.33333333]
 [0.25       0.5        0.5       ]]


Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [8]:
identity_matrix=np.identity(5,dtype=int)
extract_diagonal=np.diag(identity_matrix)
print(f"identity_matrix: \n{identity_matrix}")
print(f"Diagonal: \n{extract_diagonal}")

identity_matrix: 
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Diagonal: 
[1 1 1 1 1]


Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [9]:
a=np.random.randint(1,1000,100)

def is_prime(num):
  if num<2:
    return False
  else:
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True
prime_num=np.array([num for num in a if is_prime(num)])
prime_num


array([257, 911, 397, 499,  29, 677, 773, 373, 877, 421, 337, 823, 107,
       331])

Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [10]:
import numpy as np

daily_temperatures = np.random.randint(20, 40, 30)

weeks = daily_temperatures[:28].reshape(4, 7)  # First 4 weeks of 7 days
last_week = daily_temperatures[28:]            # Remaining 2 days

weekly_averages = np.mean(weeks, axis=1)
last_week_average = np.mean(last_week) if last_week.size > 0 else None


print("Daily Temperatures:\n", daily_temperatures)
print("\nWeekly Averages:\n", weekly_averages)

if last_week_average is not None:
    print("\nLast Week Average (for 2 days):", last_week_average)

Daily Temperatures:
 [39 22 22 29 24 20 26 39 21 20 23 35 28 36 34 27 20 32 24 26 20 22 32 30
 31 39 37 31 35 34]

Weekly Averages:
 [26.         28.85714286 26.14285714 31.71428571]

Last Week Average (for 2 days): 34.5
